# -*- coding: utf-8 -*-
"""ASED LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIUD-09YG3RwP9lBwy5yFooY6aWjioNm

Linear Regresion
"""
x=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0],[15.0],[20]]
y=[  8, 10 , 12, 14,16,18, 20, 30,40]

# --- Simple Linear Regression ---
# Step 2 - Fitting Linear Regression: Initializes and fits a standard Linear Regression model
# to the provided 'x' and 'y' data. The data represents a simple linear relationship (y = 2x).
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x,y)

# Step 4 Linear Regression prediction: Predicts the 'y' value for a new 'x' input of [[11]].
# Based on the fitted model (y=2x), the prediction should be 22.0.
print(lin_reg.predict([[11]]))

# --- Polynomial Regression (Degree 1) via Pipeline ---
# This section demonstrates performing linear regression using a pipeline that includes
# PolynomialFeatures. With degree=1 and include_bias=False, this effectively performs
# simple linear regression again.
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

polynomial_regression = make_pipeline(
    PolynomialFeatures(degree=1, include_bias=False), # Transforms input to polynomial features of degree 1
    LinearRegression(), # Applies linear regression to the transformed features
)
polynomial_regression.fit(x,y) # Fits the pipeline to the data
X_height=[[20.0]] # New input for prediction
target_predicted = polynomial_regression.predict(X_height) # Predicts 'y' for [[20.0]]
# Based on the fitted model (y=2x), the prediction should be 40.0.
print(target_predicted)

"""Polynomiall Regression (y = x^2)"""

import pandas as pd
x=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0]]
y=[  16, 25 , 36, 49,64,81, 100]
# Step 2 - Fitting Linear Regression
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x,y)

# Step 4 Linear Regression prediction
print(lin_reg.predict([[11]]))
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

polynomial_regression = make_pipeline(
    PolynomialFeatures(degree=2, include_bias=False),
    LinearRegression(),
)
polynomial_regression.fit(x,y)
X_height=[[20.0]]
target_predicted = polynomial_regression.predict(X_height)
print(target_predicted)

import pandas as pd
x=[[4.0],[5.0],[6.0],[7.0],[8.0],[9.0],[10.0]]
y=[16, 25, 36 , 49 , 64 , 81 , 100]
# Step 2 - Fitting Linear Regression
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x,y)

# Step 4 Linear Regression prediction

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

polynomial_regression = make_pipeline(
    PolynomialFeatures(degree=3, include_bias=False),
    LinearRegression(),
)
polynomial_regression.fit(x,y)
print(polynomial_regression.predict([[11]]))
X_height=[[20.0]]
target_predicted = polynomial_regression.predict(X_height)
print(target_predicted)

"""Deep Learning Linear Regression"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
x = np.array([[4],[5],[6],[7],[8],[9],[10]]) # Convert x to a NumPy array
y = np.array([8, 10 , 12, 14, 16, 18, 20]) # Convert y to a NumPy array
# Define model
model = Sequential()
model.add(Dense(1000, input_dim=1, activation= "relu"))
model.add(Dense(1000, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))
model.summary() #Print model Summarymodel.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
model.fit(x,y,epochs=200)
x=np.array([[12.0]]) # Convert x to a NumPy array for prediction
print(model.predict(x))


